using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TAIO.PSO
{
    /// <summary>
    /// Class representing velocity at the plane corresponding to one alphabet symbol.
    /// </summary>
    class PartialVelocity
    {
        // Velocities for every state on symbol's plane
        public int[] velocities
        {
            get
            {
                return velocities;
            }

            private set
            {
                velocities = value;
            }
        }

        /// <summary>
        /// Creates partial velocity for one plane.
        /// If the seed parameter is non-negative, the newly created velocity array is filled with pseud-random number generated by this seed.
        /// </summary>
        /// <param name="numberOfAutomatonStates"></param>
        /// <param name="seed"></param>
        public PartialVelocity(int numberOfAutomatonStates, int seed = -1)
        {
            velocities = new int[numberOfAutomatonStates];

            if (seed > 0)
            {
                Random rand = new Random(seed);
                for (int i = 0; i < velocities.Length; i++)
                    velocities[i] = rand.Next() % velocities.Length;
            }
        }

        /// <summary>
        /// Creates partial velocity for one plane and initializes its values.
        /// </summary>
        /// <param name="partialVelocityValues"></param>
        public PartialVelocity(int[] partialVelocityValues)
        {
            velocities = new int[partialVelocityValues.Length];

            for (int i = 0; i < partialVelocityValues.Length; i++)
                velocities[i] = partialVelocityValues[i];
        }
    }
}
